config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root "posts#index"

  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
  member do
    post 'follow', to: 'users#follow'
    delete 'unfollow', to: 'users#unfollow'
  end
end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

  resources :posts do
    resources :comments
    resources :interactions, only: %i[create destroy], controller: 'interactions'
    resources :chats

  end


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    if @user = User.find_by_email(params[:email])
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to '/login', notice: 'Sent a link to reset password!'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to '/login', alert: 'Your token has expired. Please try again'
  end

  def update
    if params[:user][:password] == params[:user][:password_confirmation]
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to '/login', allow_other_host: true, notice: 'Please sign in!'
      else
        render 'edit'
      end
    end
      rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to '/login', alert: 'Your token has expired. Please try again'
  end
 

  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/_modal.html.erb
<% if flash[:error] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:error] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div>
<% end %>
   
<% if flash[:notice] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:notice] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div> 
<% end %>
   

   
  

app/views/password_resets/_page.html.erb
<div class="container_main">     
<div class="header">
  <%= image_tag 'UrbanView.png', alt: 'Urban Image', class: 'urban_image' %>
  <h1 class="passwordReset_title">UrbanView</h1>
</div>
</div>

app/views/password_resets/edit.html.erb
<div class="container_page">
<%= render 'page' %>
<div class="passwordReset_container">
<h1>Reset your password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), class:'passwordReset_form' do |form| %>
  <div class="passwordReset">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="passwordReset">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <%= form.submit 'Reset Password',class:'passwordReset_btn' %>
<%end%>
</div>

app/views/password_resets/new.html.erb
<div class="container_page">
<%= render 'page' %>
<div class="passwordReset_container">
<h1>Forgot your password?</h1>
<%= form_with url: password_reset_path, class:'passwordReset_form' do |form| %>
    <div class="passwordReset">
    <%= form.label :email %>
    <%= form.text_field :email %>
    </div>
    <%= form.submit 'Send Reset Link', class:'passwordReset_btn' %>
<%end%>
</div>
</div>