config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root "posts#index"

  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
  member do
    post 'follow', to: 'users#follow'
    delete 'unfollow', to: 'users#unfollow'
  end
end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

  resources :posts do
    resources :comments
    resources :interactions, only: %i[create destroy], controller: 'interactions'
    resources :chats

  end


end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    
    has_one_attached :avatar

    validates :username, presence: true, uniqueness: true, length:{minimum: 3, maximum: 25}
    
    VALID_EMAIL_REGEX = /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
    
    validates :email, presence:true, length:{maximum: 125},
    format:{with: VALID_EMAIL_REGEX}
    
    has_many :comments, dependent: :destroy

    has_many :interactions, dependent: :destroy
    # has_many :interacted_posts, through: :interactions, source: :post

    has_many :followers, class_name: 'Follow', foreign_key: 'followed_id'
    has_many :following, class_name: 'Follow', foreign_key: 'follower_id'
    has_many :follower_users, through: :followers, source: :follower
    has_many :following_users, through: :following, source: :followed


    has_many :chats, dependent: :destroy

    def attended_events
      going_posts = interactions.where(option: 'going').map(&:post)
      going_posts.map {|post| { id: post.id, title: post.title } }
    end

    def hosted_events
      hosted_posts = posts.where(post_type: 'Events')
      hosted_posts.map {|post| {id: post.id, title: post.title}}
    end

    def user_interests
      interacted_posts = interactions.includes(:post).map(&:post)
      tags = interacted_posts.flat_map(&:tags_array).uniq
    end

    def published_posts
      posts
    end

    def published_posts_count
      usersPosts = posts
      usersPosts.count
    end
  
    has_secure_password
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 
   
    def show 
      @user = User.find(params[:id])
    end

    def new
    @user = User.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(updateUser_params)
        redirect_to user_path(@user), notice: 'Updated profile successfully!'
      else
        render 'edit'
      end
    end

    def create
    @user = User.new(user_params)
    
    @user.avatar.attach(io: File.open('/home/naveenprasanthv/Rails/Urbanview/UrbanView/app/assets/images/userimg.png'), filename: 'default_avatar.png', content_type: 'image/png')

    if @user.save
      if @user.password == params[:user][:password_confirmation]
          redirect_to login_path, notice: 'Registration successful!'
        else
          flash.now[:error] = "User creation failed!"
            render 'new',  status: :unprocessable_entity
        end
      else
        # flash.now[:error] = "Check the credentials entered!"
          render 'new', status: :unprocessable_entity
      end
    end

    def follow
      @user_to_follow = User.find(params[:id])
      follow = current_user.following.new(followed: @user_to_follow)
  
      if follow.save
        redirect_to post_path, notice: 'You are now following this user. You will receive mails notifying new posts!'
      end
      
    end

    def unfollow
      @user_to_unfollow = User.find(params[:id])
      follow = current_user.following.find_by(followed: @user_to_unfollow)
      
      if follow
      follow.destroy
      redirect_to post_path, notice: 'You have unfollowed this user. You will no longer receive mails notifying new posts!'
      end
    end
     
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def updateUser_params
    params.require(:user).permit(:username, :email, :location, :avatar)
  end
  
end

app/views/users/_modal.html.erb
<% if flash[:error] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:error] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div>
<% end %>
   
<% if flash[:notice] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:notice] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div> 
<% end %>
   
<% if @user.errors.any? %>
<div class="modal-container">
    <div class="modal">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <p class="modal_text">
      <ul> <% @user.errors.each do |error| %>
       <ol> <%= error.full_message %></ol>
       <% end %>
       </ul>
      </p>
      <button class="modal_btn">Close</button>
    </div>
</div> 
<% end %>

   
  

app/views/users/_page.html.erb
<div class="container_main">   
 <div class="header_main"> 
    <div class="logo_main">
    <%= image_tag 'UrbanView.png', alt: 'Urban Image', class: 'urbanImage_main' %>
    </div>
    <div class="searchBar_main">
        <%= form_with(url: posts_path(@posts), method: "get") do |form| %>
            <%= form.text_field :query %>
            <%= form.submit "Search", class:'searchBtn'%>
        <% end %>
    </div>
    
    <div class="pageButtons_main">
        <%= link_to new_post_path,title:'create new post' do %>
            <%= image_tag 'add.png', alt: 'Add Post', class: 'addImage_main' %>
        <% end %>
        <% if logged_in? && current_user_instance.avatar.attached? %>
            <%= cl_image_tag current_user_instance.avatar.key, class:'userImage_main' %>
        <% end %>  
        <div class="user_dropdown">
            <% if logged_in? %>
                <div class="user_btns">
                <%= button_to 'Account', user_path(@user), method: :get %>
                <%= button_to 'Logout', logout_path, method: :delete %>
                </div>
            <% end %>
        </div>
    </div>
    </div>
    <div class="tabNav_main">   
    <div class="tabs_main">
        <%= link_to "Events", posts_path(tab: 'Events') %>
        <%= link_to "News", posts_path(tab: 'News') %>
        <%= link_to "Jobs", posts_path(tab: 'Jobs') %>
        <%= link_to "Charity", posts_path(tab: 'Charity') %>
        <%= link_to "Explore", posts_path(tab: 'Explore') %>
    </div>   
    <div class="location_main">
        <p><span class="cityName">Select location</span><span><%= image_tag 'dropdown.png', alt: 'Dropdown', class: 'dropdownImage_main' %></span></p>
        <div class="dropdown-content">
            <input type="text" id="locationSearch" placeholder="Search cities">
            <ul id="locationList">
            <!-- City names -->
            </ul>
        </div>
    </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container_page">
 <%= render 'page' %> 

<div class="edit_profile_main">
    <div class="prevContainer">
        <span>
        <%= link_to user_path(@user), method: :get do %>
            <%= image_tag 'prev.png', alt: 'Previous', class: 'previousImage_main' %>
        <% end %>
        </span>
        <span class="prevText">Profile</span>
    </div>

    <div class="profile">
    <div class="editContainer">
      <h3>Profile Details</h3>
      <div class="editForm">
            <%= form_with(model: @user, local: true) do |form| %>
            
            <div class="editInput">
            <%= form.label :username, class: 'label' %>
            <%= form.text_field :username %>
            </div>

            <div class="editInput">
            <%= form.label :email %>
            <%= form.email_field :email %>
            </div>

            <div class="editInput">
            <%= form.label :location %>
            <%= form.text_field :location %>
            </div>

            <div class="editInput">
            <%= form.label :avatar %>
            <%= form.file_field :avatar,accept: 'image/jpeg,image/png,image/gif' %>
            </div>

            <div class="btn">
            <%= form.submit 'Update Profile', class: 'updateBtn' %>
            </div>

            <% end %>

      </div>
     
     </div>
    
    </div>
  
  </div>

</div>  

app/views/users/new.html.erb
<div class='container'>
 
 <div class="header">
  <%= image_tag 'UrbanView.png', alt: 'Urban Image', class: 'urban_image' %>
  <h1>UrbanView</h1>
 </div>

<div class="body">
 
 <div class="container_cityimage">
  <%= image_tag 'City.avif', alt: 'City Image', class: 'city_image' %>
 </div>

 <div class="container_form">

  
  <%= form_with(model: @user, local: true) do |form| %>
    
    <div class="input">
     <%= form.label :username, class: 'label' %>
     <%= form.text_field :username %>
    </div>

    <div class="input">
     <%= form.label :email %>
     <%= form.email_field :email %>
    </div>

    <div class="input">
     <%= form.label :password %>
     <%= form.password_field :password %>
    </div>

    <div class="input">
     <%= form.label :password_confirmation, "Confirm Password"  %>
     <%= form.password_field :password_confirmation %>
    </div>

    <div class="btn">
     <%= form.submit 'Sign Up', class: 'sign-btn' %>
    </div>
   
  <% end %>

   <div class="links">
    <%= link_to 'Back to SignIn!', login_path %>
    </div>

  </div>
 
 </div>

</div>

app/views/users/show.html.erb
<div class="container_page">
<%= render 'page' %>

<div class="profile_main" id="profile_main">
    
    <div class="prevContainer">
        <span>
        <%= link_to root_path(@user), method: :get do %>
            <%= image_tag 'prev.png', alt: 'Previous', class: 'previousImage_main' %>
        <% end %>
        </span>
        <span class="prevText">Home</span>
    </div>

    <div class="profileContainer">
        <div class="profileImage">
            <% if @user.avatar.attached? %>
                <%= cl_image_tag @user.avatar.key, :width=>150, :crop=>"fill" %>
            <% end %>
        </div>

        <div class="profileDetails">

             <div class="userDetails">
               <% if logged_in? %>
               <span class="profileUser">
                 <%= image_tag('profileuser.png', alt: 'user   ') %>
               <%= @user.username %></span>
               <span class="profileLocation">
                 <%= image_tag('location.png', alt: 'location') %>
               <%= @user.location %></span>
               
               
                

                <div class="accountDetails">
                <span class="followers-count"><%= @user.followers.count %> Followers</span>
                <span class="following-count"><%= @user.following.count %> Following</span>
                <span class="pusblishedPosts-count"><%=@user.published_posts_count %> Posts</span>
                 </div> 


                 <% unless current_user == @user %>
               <span class="profilefollow_unfollow-btn">
                    <% if current_user.following_users.include?(@user) %>
                        <%= form_tag unfollow_user_path(@user), method: :delete do %>
                        <%= submit_tag 'Unfollow' %>
                        <% end %>
                    <% else %>
                        <%= form_tag follow_user_path(@user), method: :post do %>
                        <%= submit_tag 'Follow' %>
                        <% end %>
                    <% end %>
                </span>
                <% end %>

                <% if current_user.id == @user.id %>
                <span class="button">
                    <%= button_to edit_user_path(@user), method: :get, class:'usereditBtn' do %>
                    <%= image_tag('edit.png', alt: 'Edit') %>
                    Edit
                    <% end %>
                </span>
                <%end%>
               <% end %>

             </div>



        <div class="accountEventDetails">
        <span class="attended-events" id="event-box">
        <h3>Attended Events</h3>
        <div class="attendedEventsSection">
        <% @user.attended_events.each do |event| %>
            <span class="event">
            <%= link_to post_path(event[:id]), class: 'attendedEvent-link' do %>
            <%= event[:title] %>
            <% end %>
            </span>
        <% end %>
        </div>
        </span>

        <span class="hosted-events" id="event-box">
        <h3>Hosted Events</h3>
        <div class="hostedEventsSection">
        <% @user.hosted_events.each do |event| %>
            <span class="event">
            <%= link_to post_path(event[:id]), class: 'attendedEvent-link' do %>
            <%= event[:title] %>
            <% end %>
            </span>
        <% end %>
        </div>
        </span>

        <span class="user-interests" id="event-box">
        <h3>User Interests</h3>
        <div class="interestsSection">
        <% @user.user_interests.each do |interest| %>
            <span class="interest">
            <%= link_to posts_path(query: interest) do%>
            <%= interest %>
            <% end %>
            </span>
        <% end %>
        </div>
        </span>
        </div> 

    </div>
</div> 
        
         <div class="user-posts">
         <h3>Posts</h3>
         <div class="userPosts">
            <% @user.published_posts.each do |post| %>
            <%= link_to post_path(post.id), class: 'userPost-link' do %>
            <div class="userPost">
                <span class="userPostImage">
                <% if post.urls.present? %>
                <%= image_tag(post.urls.first, class: 'image') %>
                <% else %>
                <%= image_tag('UrbanView.png', class: 'image') %>
                <% end %>
                </span>
                <span class="userPostDetails">
                <span class="userPostTitle">
                <h4>Title</h4>
                <%= post.title %>
                </span>
                <span class="userPostDescription">
                <h4>Description</h4> 
                <%= truncate(post.description, length: 200, separator: ' ') %> 
                </span>
                </span>
            </div>
            <% end %>
            <% end %>
            </div>
        </div> 

</div>

</div>