config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root "posts#index"

  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
  member do
    post 'follow', to: 'users#follow'
    delete 'unfollow', to: 'users#unfollow'
  end
end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

  resources :posts do
    resources :comments
    resources :interactions, only: %i[create destroy], controller: 'interactions'
    resources :chats

  end


end

app/models/post.rb
class Post < ApplicationRecord

    # validate :valid_tags
    
    # has_one_attached :postImages

    store :imageUrls, accessors: [:urls], coder: JSON
    after_initialize do
        self.urls ||= []
    end

    store :videoUrls, accessors: [:videourls], coder: JSON
    after_initialize do
        self.videourls ||= []
    end

    validates :title, presence: true, length: {minimum: 4, maximum: 60}
    validates :description, presence: true, length: {minimum: 10, maximum: 5000}
    validates :tags, presence: true
    validates :location, presence: true
    validates :post_type, presence: true,inclusion: {in:['Events','Jobs','Charity','Explore']}
    validate :valid_event_dates

    belongs_to :user

    has_many :comments, dependent: :destroy
   
    has_many :interactions, dependent: :destroy
    has_many :interactors, through: :interactions, source: :user
     
    has_many :chats, dependent: :destroy
    
    def tags_array
        tags.split(',').map(&:strip)
    end

    def going_count
       interactions.where(option: 'going').count
    end

    def not_going_count
        interactions.where(option: 'not_going').count
    end

    def maybe_count
        interactions.where(option: 'maybe').count
    end

    def donated_count
        interactions.where(option: 'donated').count
    end

    def like_count
        interactions.where(option: 'like').count
    end

    def dislike_count
        interactions.where(option: 'dislike').count
    end

    def selected_option(user)
        interaction = interactions.find_by(user_id: user.id)
        interaction&.option
    end

    def event_status
        current_time = Time.now.utc
        start_date_utc = start_date.utc if start_date.present?
        end_date_utc = end_date.utc if end_date.present?
      
        if start_date_utc.present? && end_date_utc.present?
          if current_time < start_date_utc
            'Upcoming'
          elsif current_time >= start_date_utc && current_time <= end_date_utc
            'Ongoing'
          else
            'Ended'
          end
      end
    end


    private

    # def valid_tags
    #     valid_values = %w(Events News Jobs Charity events news jobs charity)
    #     valid_tags_array = tags_array.select { |tag| valid_values.include?(tag) }
    #     unless valid_tags_array.length == 1
    #     errors.add(:tags, "should contain exactly one of: #{valid_values.join(', ')}")
    #     end
    # end

    def event_enabled?
        enable_event == true
    end

    def valid_event_dates
        return unless event_enabled?

        if start_date.present? && end_date.present? && start_date > end_date
        errors.add(:end_date, 'must be after the start date')
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:index] 
  
    def show
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @post = Post.find(params[:id])
    end

    def index 
        if session[:user_id]
            @user = User.find(session[:user_id])
        end

        if params[:query].present?
            @posts = Post.where("title LIKE ? OR description LIKE ? OR location LIKE ? OR tags LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%")
          else
            @active_tab = params[:tab]
            case params[:tab]
            when 'Events'
              @posts = Post.where("post_type LIKE ? AND location LIKE ?", "%Events%", "%#{params[:location]}%")
            when 'News'
              @posts = Post.where("post_type LIKE ? AND location LIKE ?", "%News%", "%#{params[:location]}%")
            when 'Jobs'
              @posts = Post.where("post_type LIKE ? AND location LIKE ?", "%Jobs%", "%#{params[:location]}%")
            when 'Charity'
              @posts = Post.where("post_type LIKE ? AND location LIKE ?", "%Charity%", "%#{params[:location]}%")
            when 'Explore'
              @posts = Post.all
            else
              @posts = Post.where("location LIKE ?", "%#{params[:location]}%")
            end
          end

    end

    def new 
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @post = Post.new
    end

    def edit
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @post = Post.find(params[:id])
    end

    def create
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            if params[:post][:images].present? && params[:post][:images].length > 1
                params[:post][:images].drop(1).each do |image|
                upload_result = Cloudinary::Uploader.upload(image)
                @post.urls << (upload_result['secure_url'])
                @post.save
                end
            else
                upload_result = Cloudinary::Uploader.upload('https://images3.alphacoders.com/133/1337543.png')
                @post.urls << (upload_result['secure_url'])
                @post.save
            end
            if params[:post][:videos].present?
             
              params[:post][:videos].drop(1).each do |video|
              videoupload_result = Cloudinary::Uploader.upload_large(video, :resource_type => :video,
              :quality => 'auto',
              :transformation => { streaming_profile: 'auto',format: 'm3u8' })
              @post.videourls << (videoupload_result['public_id'])
              @post.save
              end
            end
            current_user.followers.each do |follower|
            user = follower.follower
            PostMailer.new_post_notification(user, @post).deliver_now
        end
            redirect_to @post, notice: 'Post was successfully created.'
        else
      
            render :new,status: :unprocessable_entity
        end
        
    end

    def update 
        if session[:user_id]
            @user = User.find(session[:user_id])
        end

        @post = Post.find(params[:id])
        
        delete_image_indices = extract_indices(params[:post])
        urls_array = @post.urls
        delete_image_indices.each { |index| urls_array.delete_at(index) }

        if params[:post][:images].present?
            params[:post][:images].drop(1).each do |image|
            upload_result = Cloudinary::Uploader.upload(image)
            @post.urls << (upload_result['secure_url'])
            end
        end

        if @post.update(post_params) 
            redirect_to @post, notice: 'Post was successfully updated.'
          else
            render :edit
          end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private

    def post_params
      params.require(:post).permit(:title, :description, :location, :tags, :video,:enable_event, :start_date, :end_date, :post_type)
    end

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end

    def extract_indices(post_params)
      delete_image_params = post_params.select { |key, value| key.starts_with?('delete_image_') && value == '1' }
      delete_image_params.keys.map { |key| key.scan(/\d+/).first.to_i }
    end
end

app/views/posts/_modal.html.erb
<% if flash[:error] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:error] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div>
<% end %>
   
<% if flash[:notice] %>
<div class="modal-container">
    <div class="modal">
      <p class="modal_text"><%= flash[:notice] %></p>
      <button class="modal_btn">Close</button>
    </div>
</div> 
<% end %>
   
<% if @post.present? && @post.errors.any? %>
<div class="modal-container">
    <div class="modal">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <p class="modal_text">
      <ul> <% @post.errors.each do |error| %>
       <ol> <%= error.full_message %></ol>
       <% end %>
       </ul>
      </p>
      <button class="modal_btn">Close</button>
    </div>
</div> 
<% end %>

   
  

app/views/posts/_page.html.erb
<div class="container_main">   
 <div class="header_main"> 
    <div class="logo_main">
    <%= image_tag 'UrbanView.png', alt: 'Urban Image', class: 'urbanImage_main' %>
    </div>
    <div class="searchBar_main">
        <%= form_with(url: posts_path(@posts), method: "get") do |form| %>
            <%= form.text_field :query %>
            <%= form.submit "Search", class:'searchBtn'%>
        <% end %>
    </div>
    
    <div class="pageButtons_main">
        <%= link_to new_post_path,title:'create new post' do %>
            <%= image_tag 'add.png', alt: 'Add Post', class: 'addImage_main' %>
        <% end %>
        <% if logged_in? && @user.avatar.attached? %>
            <%= cl_image_tag @user.avatar.key, class:'userImage_main' %>
        <% end %>  
        <div class="user_dropdown">
            <% if logged_in? %>
                <div class="user_btns">
                <%= button_to 'Account', user_path(@user), method: :get %>
                <%= button_to 'Logout', logout_path, method: :delete %>
                </div>
            <% end %>
        </div>
    </div>
    </div>
    <div class="tabNav_main">   
    <div class="tabs_main">
        <%= link_to "Events", posts_path(tab: 'Events'),class:('selectedTab' if @active_tab == "Events") %>
        <%= link_to "News", posts_path(tab: 'News'),class:('selectedTab' if @active_tab == "News") %>
        <%= link_to "Jobs", posts_path(tab: 'Jobs'),class:('selectedTab' if @active_tab == "Jobs") %>
        <%= link_to "Charity", posts_path(tab: 'Charity'),class:('selectedTab' if @active_tab == "Charity") %>
        <%= link_to "Explore", posts_path(tab: 'Explore'),class:('selectedTab' if @active_tab == "Explore") %>
    </div>   
    <div class="location_main">
        <p><span class="cityName">Select location</span><span><%= image_tag 'dropdown.png', alt: 'Dropdown', class: 'dropdownImage_main' %></span></p>
        <div class="dropdown-content">
            <input type="text" id="locationSearch" placeholder="Search cities">
            <ul id="locationList">
            <!-- City names -->
            </ul>
        </div>
    </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container_page">
<%= render 'page' %>

<div class="container_editpost">
    <div class="prevContainer">
        <span>
        <%= link_to post_path(@post), method: :get do %>
            <%= image_tag 'prev.png', alt: 'Previous', class: 'previousImage_main' %>
        <% end %>
        </span>
        <span class="prevText">Back to Post</span>
    </div>
<div class="editpostContainer">
    <h3>Edit Post</h3>
    <div class="editpostForm">
        <%= form_with(model: @post,local: true) do |form| %>
            <div class="editpostInput">
                <%= form.label :title %>
                <%= form.text_field :title %>
            </div>
            <div class="editpostInput">
                <%= form.label :description %>
                <%= form.text_area :description %>
            </div>
            <div class="editpostInput">
                <%= form.label :location %>
                <%= form.text_field :location %>
            </div>
            <div class="editpostInput">
                <%= form.label :tags %>
                <%= form.text_field :tags %>
            </div>
            <div class="editpostInput">
                <%= form.label :postImages %>
                <div class="editpostImagesup">
                    <div> 
                    <%= form.file_field :images, multiple: true %>
                    </div>
                    <div class="editpostImages">
                        <% @post.urls.each_with_index do |url, index| %>
                        <div class="editpostImage">
                            <%= image_tag(url, width: '50px') %>
                            <%= form.check_box "delete_image_#{index}" %>
                            <%= form.label "delete_image_#{index}", "Delete",class:'imageCheckboxText' %>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="createInput">
                <%= form.label :enable_event, class:'enable-event-label' %>
                <%= form.check_box :enable_event, class:'enable-event-checkbox' %>
            </div>

            <div class="event-dates">
                <div class="createInput">
                <%= form.label :start_date %>
                <%= form.datetime_local_field :start_date, disabled: !@post.enable_event %>
                </div>

                <div class="createInput">
                <%= form.label :end_date %>
                <%= form.datetime_local_field :end_date, disabled: !@post.enable_event %>
                </div>
            </div>
            <div class="editpostInput">
                <%= form.submit 'Update Post', class:'editpostBtn' %>
            </div>
        <% end %>
    </div>
</div>
</div>
</div>

app/views/posts/index.html.erb
<div class="container_page" >
<%= render 'page' %>
<div class="container_posts">

<% @posts.each do |post| %>
<%= link_to post_path(post),class:'postLink' do%> 
<div class="posts_card">
 <div class="post" id="post_<%= post.id %>" data-post-id="<%= post.id %>">
  <div class="postStatus">
    <% if post.event_status.present? %>
    <span class="event_status  
    <%= 'status_Ended' if post.event_status == 'Ended' %>
    <%= 'status_Upcoming' if post.event_status == 'Upcoming' %>
    <%= 'status_Ongoing' if post.event_status == 'Ongoing' %>">
    <%= post.event_status %></span>
    <%end%>
  </div>
    <div class="postImage">
      <% if post.urls.present? %>
      <%= image_tag(post.urls.first, class: 'image') %>
      <% else %>
      <%= image_tag('UrbanView.png', class: 'image') %>
      <% end %>
      
      <% if post.going_count > 0 && post.post_type == 'Events' %>
      <span class="interaction_count" ><span id="post_<%= post.id%>_going"><%= post.going_count %> going </span>
      <%= image_tag('animated_gif.gif',class: 'animated_gif') %>
      </span>
      <% end %>
       
      <% if post.donated_count > 0 && post.post_type == 'Charity' %>
      <span class="interaction_count" ><span id="post_<%= post.id%>_donated"><%= post.donated_count %> donated</span>
      <%= image_tag('charity_gif.gif',class: 'animated_gif') %>
      </span>
      <% end %>

      <% if post.like_count > 0 %>
      <span class="interaction_count"><span id="post_<%= post.id%>_like"><%= post.like_count %> liked</span>
      <%= image_tag('like_gif.gif',class: 'animated_gif') %>
      </span>
      <% end %>

    </div>
 
  <div class="postTags">
    <% post.tags_array.each do |tag| %>
    <span class="tags"><%= tag %></span>
    <% end %>
  </div>
  <div class="postTitle">
    <p><%= post.title%> 
    <span class="postDescriptionlink"> 
    </span></p>
  </div>
   <div class="postDescription">
    <p><%= truncate(post.description, length: 70, separator: ' ') %> 
    <span class="postDescriptionlink">
    
    </span></p>
  </div>
  <div class="postUser">
    <span class="postUser_user">
      <span>
        <% if post.user.avatar.attached? %>
              <%= cl_image_tag post.user.avatar.key, class:'postAvatar' %>
        <% end %>
      </span>
      <span>
          &nbsp;@<%= post.user.username %>
      </span>
      &nbsp;
      &middot;
      &nbsp;
      <span>
          <%= post.created_at.strftime('%d %b %y') %>
      </span>
      </span>
      <span>
      <button class="index-share-button" data-title="<%= post.title %>" data-text="<%= post.description %>" data-url="<%= post_url(post) %>">
        <%= image_tag('index_share.png', alt: 'Share Post') %>
      </button>
      </span>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container_page">
<%= render 'page' %>

<div class="container_createpost">
    <div class="prevContainer">
        <span>
        <%= link_to posts_path(@post), method: :get do %>
            <%= image_tag 'prev.png', alt: 'Previous', class: 'previousImage_main' %>
        <% end %>
        </span>
        <span class="prevText">Posts</span>
    </div>
<div class="createContainer">
    <h3>Create new Post</h3>
    <div class="createForm">
    <%= form_with model: @post, url: posts_path,local: true do |form| %>
    <div class="createInput">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div class="createInput">
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div class="createInput">
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div>
    <div class="createInput">
        <%= form.label :tags %>
        <%= form.text_field :tags %>
    </div>
    <div class="createInput">
        <%= form.label :postImages %>
        <%= form.file_field :images, multiple: true,accept: 'image/jpeg,image/png,image/gif'%>
    </div>
    <div class="createInput">
        <%= form.label :postVideos %>
        <%= form.file_field :videos, multiple: true%>
    </div>
     <div class="createInput">
        <%= form.label :post_type %>
        <%= form.select :post_type, ['Events','News','Jobs','Charity','Explore'],{},{class: 'post_typeDropdown'} %>
     </div>
    <div class="createInput">
        <%= form.label :enable_event, class:'enable-event-label' %>
        <%= form.check_box :enable_event, class:'enable-event-checkbox' %>
    </div>

    <div class="event-dates">
        <div class="createInput">
        <%= form.label :start_date %>
        <%= form.datetime_local_field :start_date, disabled: !@post.enable_event %>
        </div>

        <div class="createInput">
        <%= form.label :end_date %>
        <%= form.datetime_local_field :end_date, disabled: !@post.enable_event %>
        </div>
    </div>

    <div class="createInput">
        <%= form.submit 'Create Post',class:'createBtn' %>
    </div>
    <% end %>
    </div>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="container_page">
<%= render 'page' %>

<div class="container_detailpost">
    <div class="prevContainer">
        <span>
        <%= link_to posts_path(@post), method: :get do %>
            <%= image_tag 'prev.png', alt: 'Previous', class: 'previousImage_main' %>
        <% end %>
        </span>
        <span class="prevText">Back to Home</span>
    </div>

  <div class="detailContainer" > 
    <div class="detailUser">
    <div class="postTitle">
      <h1><%= @post.title %></h1> 
    <div class="postButtons">
      <button class="share-post-button" data-title="<%= @post.title %>" data-text="<%= @post.description %>" data-url="<%= post_url(@post) %>">
        <%= image_tag('share.png', alt: 'Share Post') %> Share Post
      </button>
      
      <% if logged_in? && @post.user == current_user %>
      <div class="menuIcon">
          <%= image_tag('menu.png', alt: 'Menu') %>
          <div class="postControls">    
            <%= button_to('Edit', edit_post_path(@post), method: :get, class: 'edit-post-button') %>
            <%= button_to('Delete', @post, method: :delete, class: 'delete-post-button',onclick: "return confirm('Are you sure?');") %>
          </div>
      </div>
     <% end %>
  
    </div>
 
    </div>  
    <div class="detailuserSection">
      <div class="user">
        <span class="userLogo">
          <% if @post.user.avatar.attached? %>
                <%= cl_image_tag @post.user.avatar.key, class:'detailAvatar' %>
          <% end %>
        </span>
        <span class="userData">
        
        <span>
          <%= link_to user_path(@post.user), class: 'user_profile-link' do %>
            @<%= @post.user.username %>
          <% end %>
        </span>

          <span>
              Posted on <%= @post.created_at.strftime('%d %B %Y') %>
          </span>
        </span>
        <span class="follow_unfollow-btn">
            <% unless current_user == @post.user %>
              <% if current_user.following_users.include?(@post.user) %>
                <%= form_tag unfollow_user_path(@post.user), method: :delete do %>
                <%= submit_tag 'Unfollow' %>
                <% end %>
              <% else %>
                <%= form_tag follow_user_path(@post.user), method: :post do %>
                <%= submit_tag 'Follow' %>
                <% end %>
              <% end %>
            <% end %>
        </span>
      </div>

      <div class="interactionButtons" id="interactionButtons" data-post-id="<%= @post.id %>" data-user-id="<%= current_user.id %>">

         <% if @post.post_type == 'Events' %>
          <%= button_to(post_interactions_path(@post, option: 'going'), method: :post, class: "like-post-button #{'selected' if @post.selected_option(current_user) == 'going'}") do %>
             <span>🙌</span>
            <span id="going_count"><%= @post.going_count %> Going</span>
          <% end %>

          <%= button_to(post_interactions_path(@post, option: 'not_going'), method: :post, class: "dislike-post-button #{'selected' if @post.selected_option(current_user) == 'not_going'}") do %>
             <span>😔</span>
            <span id="not_going_count"><%= @post.not_going_count %> Not going</span>
          <% end %>

          <%= button_to(post_interactions_path(@post, option: 'maybe'), method: :post, class: "maybe-post-button #{'selected' if @post.selected_option(current_user) == 'maybe'}") do %>
            <span>😶‍🌫️</span>
            <span id="maybe_count"><%= @post.maybe_count %> Maybe</span>
          <% end %>

        <% elsif @post.post_type == 'Charity'  %>
          <%= button_to(post_interactions_path(@post, option: 'donated'), method: :post, class: "like-post-button #{'selected' if @post.selected_option(current_user) == 'donated'}") do %>
            <span>💗</span>
            <span id="donated_count"><%= @post.donated_count %> Donated</span>
          <% end %>

        <% else %>
          <%= button_to(post_interactions_path(@post, option: 'like'), method: :post, class: "like-post-button #{'selected' if @post.selected_option(current_user) == 'like'}") do %>
            <%= image_tag('like.png', alt: 'like') %>
            <span id="like_count"><%= @post.like_count %> Likes</span>
          <% end %>

          <%= button_to(post_interactions_path(@post, option: 'dislike'), method: :post, class: "dislike-post-button #{'selected' if @post.selected_option(current_user) == 'dislike'}") do %>
            <%= image_tag('dislike.png', alt: 'Notgoing') %>
            <span id="dislike_count"><%= @post.dislike_count %> Dislikes</span>
          <% end %>
        <% end %>

  
      </div>  
    </div>
    </div>

    <% if@post.videourls.count > 0 %>
     <div class="detailLiveSection">
      
      <div class="detailVideoStreamer shadow">
        <% @post.videourls.each do |url| %>
          <%= cl_video_tag(url, :cloud_name => 'dqrt7ghqi', :id => 'cloudinary-video-player', :controls => true) %>
        <% end %>
      </div>

      <div class="detailLiveChat">
        <div id="chat-section" class="chat-section" data-post-id="<%= @post.id %>" data-user-id="<%= current_user.id %>">
        <%= render partial: 'chats/chat', collection: @post.chats %>
        </div>
        <%= form_with(model: [@post, Chat.new], id: 'new-chat-form', remote: true) do |f| %>
          <%= f.text_area :content, placeholder: 'Type your message here', id: 'chat_content' %>
          <%= f.submit 'Send' %>
        <% end %>
      </div>
      
    </div>

    <% elsif@post.urls.count > 0 %>
    <div class="detailImagesSlider">
      <% @post.urls.each do |url| %>
        <%= image_tag(url, width: '100px') %>
      <% end %>
    </div>
    
    <% end %>

    <% if @post.post_type == 'Events' %>
        <div class="interactionButtonsSection">
          Share your decision:
          <%= button_to(post_interactions_path(@post, option: 'going'), method: :post, class: "like-post-button") do %>
            <span>🙌</span>
            <span> Going</span>
          <% end %>

          <%= button_to(post_interactions_path(@post, option: 'not_going'), method: :post, class: "dislike-post-button") do %>
            <span>😔</span>
            <span> Not going</span>
          <% end %>

          <%= button_to(post_interactions_path(@post, option: 'maybe'), method: :post, class: "maybe-post-button") do %>
            <span>😶‍🌫️</span>
            <span> Maybe</span>
          <% end %>
          </div>
    <% end %>
    
    <div class="descriptionContainer">
      <div class="descriptionHeading">
        <h2>Description</h2>
      </div>
      <div class="description">
      <div class="detailDescription">
      <%= simple_format(@post.description) %>
      </div>
      </div>
    </div>

    <div class="tagsSection">
      <div class="tagsHeading">
        <h2>Tags</h2>
      </div>
      <% @post.tags_array.each do |tag| %>
        <span class="tags"><%= tag %></span>
      <% end %>
    </div>

    <div class="comments">

      <div class="commentsHeading">
        <h2>Comments</h2>
      </div>

      <div class="commentsSection">
    
      <div class="commentsForm">
        <div class="commentsForm_userLogo">
          <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, class:'commentAvatar' %>
          <% end %>
        </div>
        <div class="commentsForm_form">
          <%= form_for [@post, Comment.new] do |f| %>
          <%= f.text_area :content, placeholder: 'Add a comment' %>
          <%= f.submit 'Submit',class:'commentSubmitbtn' %>
          <% end %>
         </div>
      </div>
    
      <div class="commentsList">
    
       <% @post.comments.each do |comment| %>
       
       <div class="comment">
        <div class="commentUser">
            <div class="commentUser_userLogo">
            <% if comment.user.avatar.attached? %>
            <%= cl_image_tag comment.user.avatar.key, class:'commentAvatar' %>
            <% end %>
            </div>
          
        </div>
        <div class="commentContent">
          <div class="commentContent_user">
            <%= comment.user.username %>&nbsp;&middot;&nbsp;<%= comment.created_at.strftime('%d %b %y') %>
            <div class="commentControls">
                <% if comment.user == current_user %>
                <%= button_to(edit_post_comment_path(@post, comment), method: :get, class: 'edit-button') do %>
                <%= image_tag('edit.png', alt: 'Edit') %>
                <% end %>
                <%= button_to(post_comment_path(@post, comment), method: :delete, class: 'delete-button', onclick: "return confirm('Are you sure?');") do %>
                <%= image_tag('delete.png', alt: 'Delete') %>
                <% end %>
                <% end %>
             </div>
          </div>
          <div class="commentContent_content">
            <%= comment.content %>
          </div>
        </div>

        
       </div>

    <% end %>
    </div>

  </div>
  </div>

</div>
</div>
</div>